version: '3.4'

services:
  utopia2.0:
    image: ${DOCKER_REGISTRY-}utopia20
    build:
      context: .
      dockerfile: Utopia2.0/Dockerfile
    ports:
      - "8000:80"
    depends_on:
          - Utopia

  Utopia:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"